Cu 2y2yyma gh 127  field 71 b in mt590 component narrative
prowide/prowide-core pull request #135
Opened 2022-11-09 22:15 UTC by ptorres-prowide

2022-11-09 22:15 UTC, zubri commented
Task linked: [CU-2y2yyma GH-127 ⁃ Field 71B in MT590 component narrative](https://app.clickup.com/t/2y2yyma)

2022-11-14 17:04 UTC, zubri requested changes

2022-11-14 17:04 UTC, zubri commented on src/main/java/com/prowidesoftware/swift/model/field/Field.java
> +    public String toJsonNarrative() {
no publico en lo posible

2022-11-14 17:04 UTC, zubri commented on src/main/java/com/prowidesoftware/swift/model/field/NarrativeResolver.java
> +    private static boolean isCurrencyAndAmount(String text) {
meter junit

2022-11-14 17:04 UTC, zubri commented on src/main/java/com/prowidesoftware/swift/model/field/NarrativeResolver.java
> +            if (!Character.isUpperCase(textWithoutBankCode.charAt(i))) {
index out of bound?

2022-11-14 17:04 UTC, zubri commented on src/main/java/com/prowidesoftware/swift/model/field/NarrativeResolver.java
> +        String textWithoutBankCode = (Character.isUpperCase(text.charAt(0)) && (text.charAt(1) == '/'))
podes tambien poner de entrada que si no tiene al menos 4 caracteres de longitud devuelva false

2022-11-14 17:04 UTC, zubri commented on src/main/java/com/prowidesoftware/swift/model/field/StructuredNarrativeField.java
> +        return super.toJson().substring(0, super.toJson().length() - 1) + ","
metele el json en un var local para no llamarlo dos veces

2022-11-14 18:35 UTC, ptorres-prowide commented on src/main/java/com/prowidesoftware/swift/model/field/StructuredNarrativeField.java
> +        return super.toJson().substring(0, super.toJson().length() - 1) + ","
Ok

2022-11-14 18:36 UTC, ptorres-prowide commented on src/main/java/com/prowidesoftware/swift/model/field/NarrativeContainerJsonUtils.java
>      private static int countNarrativesInJson(String json) {
Ok

2022-11-15 14:10 UTC, zubri approved these changes

2022-11-15 14:11 UTC, merged